[package]
name = "wadm-cli"
description = "wasmCloud Application Deployment Manager: A tool for running Wasm applications in wasmCloud"
version = "0.13.0-beta.2"
edition = "2021"
authors = ["wasmCloud Team"]
keywords = ["webassembly", "wasmcloud", "wadm"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/wasmcloud/wadm"

[features]
default = []
# internal feature for e2e tests
_e2e_tests = []

[workspace]
members = ["crates/*"]

[dependencies]
anyhow = { workspace = true }
async-nats = { workspace = true }
async-trait = { workspace = true }
clap = { workspace = true, features = ["derive", "cargo", "env"] }
futures = { workspace = true }
nkeys = { workspace = true }
# One version back to avoid clashes with 0.10 of otlp
opentelemetry = { workspace = true, features = ["rt-tokio"] }
# 0.10 to avoid protoc dep
opentelemetry-otlp = { workspace = true, features = [
    "http-proto",
    "reqwest-client",
] }
schemars = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true, features = ["log"] }
tracing-futures = { workspace = true }
tracing-opentelemetry = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter", "json"] }
wasmcloud-control-interface = { workspace = true }
wadm = { workspace = true }
wadm-types = { workspace = true }

[workspace.dependencies]
anyhow = "1"
async-nats = "0.33"
async-trait = "0.1"
base64 = "0.21.2"
bytes = "1"
chrono = "0.4"
clap = { version = "4", features = ["derive", "cargo", "env"] }
cloudevents-sdk = "0.7"
futures = "0.3"
indexmap = { version = "2", features = ["serde"] }
jsonschema = "0.17"
lazy_static = "1"
nkeys = "0.3.0"
# One version back to avoid clashes with 0.10 of otlp
opentelemetry = { version = "0.17", features = ["rt-tokio"] }
# 0.10 to avoid protoc dep
opentelemetry-otlp = { version = "0.10", features = [
    "http-proto",
    "reqwest-client",
] }
rand = { version = "0.8", features = ["small_rng"] }
regex = "1.9.3"
schemars = "0.8"
semver = { version = "1.0.16", features = ["serde"] }
serde = "1"
serde_json = "1"
serde_yaml = "0.9"
sha2 = "0.10.2"
thiserror = "1"
tokio = { version = "1", default-features = false }
tracing = { version = "0.1", features = ["log"] }
tracing-futures = "0.2"
tracing-opentelemetry = { version = "0.17" }
tracing-subscriber = { version = "0.3.7", features = ["env-filter", "json"] }
ulid = { version = "1", features = ["serde"] }
utoipa = "4"
uuid = "1"
wadm = { version = "0.13.0-beta.2", path = "./crates/wadm" }
wadm-client = { version = "0.2.0-beta.2", path = "./crates/wadm-client" }
wadm-types = { version = "0.2.0-beta.2", path = "./crates/wadm-types" }
wasmcloud-control-interface = "1.0.0"
wasmcloud-secrets-types = "0.2.0"
wit-bindgen-wrpc = { version = "0.3.7", default-features = false }

[dev-dependencies]
base64 = { workspace = true }
chrono = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
serial_test = "3"
wadm-client = { workspace = true }
wadm-types = { workspace = true }

[build-dependencies]
schemars = { workspace = true }
serde_json = { workspace = true }
wadm-types = { workspace = true }

[[bin]]
name = "wadm"
path = "src/main.rs"

[[bin]]
name = "wadm-schema"
path = "src/schema.rs"
