apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: my-example-app
  annotations:
    description: "This is my app revision 2"
spec:
  components:
    - name: userinfo
      type: component
      properties:
        image: wasmcloud.azurecr.io/fake:1
      traits:
        # NOTE: This demonstrates what a custom scaler could look like. This functionality does not currently exist
        - type: customscaler
          properties:
            instances: 4
            clouds:
              - aws
              - azure
            scale_profile: mini

    - name: webcap
      type: capability
      properties:
        image: wasmcloud.azurecr.io/httpserver:0.13.1
      traits:
        - type: link
          properties:
            target:
              name: userinfo
            namespace: wasi
            package: http
            interfaces:
              - incoming-handler
            source:
              config:
                - name: default-port
                  properties:
                    port: "8080"
