apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: my-example-app
  annotations:
    version: v0.0.2
    description: "This is my app revision 2"
spec:
  components:
    - name: userinfo
      type: actor
      properties:
        image: wasmcloud.azurecr.io/fake:1
      traits:
        # NOTE: This demonstrates what a custom scaler could look like. This functionality does not currently exist
        - type: customscaler
          properties:
            instances: 4
            clouds:
              - aws
              - azure
            scale_profile: mini
        - type: linkdef
          properties:
            target: webcap
            values:
              port: "8080"

    - name: webcap
      type: capability
      properties:
        contract: wasmcloud:httpserver
        image: wasmcloud.azurecr.io/httpserver:0.13.1
        link_name: default
