apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: echo
  annotations:
    description: 'This is my app'
spec:
  components:
    - name: echo
      type: component
      properties:
        image: wasmcloud.azurecr.io/echo:0.3.7
      traits:
        - type: spreadscaler
          properties:
            instances: 1

    - name: httpserver
      type: capability
      properties:
        image: wasmcloud.azurecr.io/httpserver:0.17.0
      traits:
        - type: spreadscaler
          properties:
            instances: 1
        - type: link
          properties:
            target:
              name: echo
            namespace: wasi
            package: http
            interfaces:
              - incoming-handler
            source:
              config:
                - name: default-port
                  properties:
                    address: 0.0.0.0:8080
