[package]
name = "wadm-types"
description = "Types and validators for the wadm API"
version = "0.7.1"
edition = "2021"
authors = ["wasmCloud Team"]
keywords = ["webassembly", "wasmcloud", "wadm"]
license = "Apache-2.0"
repository = "https://github.com/wasmcloud/wadm"

[features]
default = []
wit = ["wit-bindgen-wrpc"]

[dependencies]
serde_yaml = { workspace = true }
anyhow = { workspace = true }
regex = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["full"] }
utoipa = { workspace = true }
wit-bindgen-wrpc = { workspace = true, optional = true }
